2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Configure stats pid to 132089
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Loading settings from /home/ale/.config/wandb/settings
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Loading settings from /home/ale/project-sim2real-montana-scavone/Extension_walker_2D/UDR/wandb/settings
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'custom-walker-ppo', 'entity': 'alex-scavone-politecnico-di-torino', 'root_dir': '/home/ale/project-sim2real-montana-scavone/Extension_walker_2D/UDR', 'run_id': 'yyxzmzrc', 'sweep_param_path': '/home/ale/project-sim2real-montana-scavone/Extension_walker_2D/UDR/wandb/sweep-vikd6hg9/config-yyxzmzrc.yaml', 'sweep_id': 'vikd6hg9'}
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Extension_walker_2D/UDR/train.py', 'program_abspath': '/home/ale/project-sim2real-montana-scavone/Extension_walker_2D/UDR/train.py', 'program': '/home/ale/project-sim2real-montana-scavone/Extension_walker_2D/UDR/train.py'}
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:_log_setup():521] Logging user logs to ./logs_train/run_0/wandb/run-20250123_161351-yyxzmzrc/logs/debug.log
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:_log_setup():522] Logging internal logs to ./logs_train/run_0/wandb/run-20250123_161351-yyxzmzrc/logs/debug-internal.log
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:init():561] calling init triggers
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:init():568] wandb.init called with sweep_config: {'delta': 0.3}
config: {}
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:init():611] starting backend
2025-01-23 16:13:51,793 INFO    Thread-9  :132089 [wandb_init.py:init():615] setting up manager
2025-01-23 16:13:51,795 INFO    Thread-9  :132089 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-23 16:13:51,795 INFO    Thread-9  :132089 [wandb_init.py:init():623] backend started and connected
2025-01-23 16:13:51,799 INFO    Thread-9  :132089 [wandb_run.py:_config_callback():1347] config_cb None None {'delta': 0.3}
2025-01-23 16:13:51,800 INFO    Thread-9  :132089 [wandb_init.py:init():715] updated telemetry
2025-01-23 16:13:51,808 INFO    Thread-9  :132089 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-01-23 16:13:52,133 INFO    Thread-9  :132089 [wandb_run.py:_on_init():2357] communicating current version
2025-01-23 16:13:52,197 INFO    Thread-9  :132089 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.19.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-01-23 16:13:52,197 INFO    Thread-9  :132089 [wandb_init.py:init():799] starting run threads in backend
2025-01-23 16:13:52,672 INFO    Thread-9  :132089 [wandb_run.py:_console_start():2335] atexit reg
2025-01-23 16:13:52,673 INFO    Thread-9  :132089 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2025-01-23 16:13:52,673 INFO    Thread-9  :132089 [wandb_run.py:_redirect():2255] Wrapping output streams.
2025-01-23 16:13:52,673 INFO    Thread-9  :132089 [wandb_run.py:_redirect():2280] Redirects installed.
2025-01-23 16:13:52,673 INFO    Thread-9  :132089 [wandb_init.py:init():842] run started, returning control to user process
2025-01-23 16:13:52,682 INFO    Thread-9  :132089 [wandb_run.py:_finish():2064] finishing run alex-scavone-politecnico-di-torino/custom-walker-ppo/yyxzmzrc
2025-01-23 16:13:52,682 INFO    Thread-9  :132089 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 1
2025-01-23 16:13:52,682 INFO    Thread-9  :132089 [wandb_run.py:_restore():2287] restore
2025-01-23 16:13:52,682 INFO    Thread-9  :132089 [wandb_run.py:_restore():2293] restore done
