2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_setup.py:_flush():68] Configure stats pid to 1617
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_setup.py:_flush():68] Loading settings from /home/vince/.config/wandb/settings
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_setup.py:_flush():68] Loading settings from /home/vince/project-sim2real-montana-scavone/PPO/wandb/settings
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_init.py:_log_setup():523] Logging user logs to ./source_logs_train/run_0/wandb/run-20250116_133310-ji9jkrkw/logs/debug.log
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_init.py:_log_setup():524] Logging internal logs to ./source_logs_train/run_0/wandb/run-20250116_133310-ji9jkrkw/logs/debug-internal.log
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_init.py:init():641] calling init triggers
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_init.py:init():647] wandb.init called with sweep_config: {'clip_range': 0.2648629139607879, 'ent_coef': 0.012416831396672916, 'learning_rate': 0.0006165903606231896}
config: {}
2025-01-16 13:33:10,648 INFO    Thread-2  :1617 [wandb_init.py:init():674] starting backend
2025-01-16 13:33:10,865 INFO    Thread-2  :1617 [wandb_init.py:init():678] sending inform_init request
2025-01-16 13:33:10,897 INFO    Thread-2  :1617 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-16 13:33:10,897 INFO    Thread-2  :1617 [wandb_init.py:init():693] backend started and connected
2025-01-16 13:33:10,898 INFO    Thread-2  :1617 [wandb_run.py:_config_callback():1283] config_cb None None {'clip_range': 0.2648629139607879, 'ent_coef': 0.012416831396672916, 'learning_rate': 0.0006165903606231896}
2025-01-16 13:33:10,900 INFO    Thread-2  :1617 [wandb_init.py:init():786] updated telemetry
2025-01-16 13:33:10,907 INFO    Thread-2  :1617 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-16 13:33:11,481 INFO    Thread-2  :1617 [wandb_init.py:init():868] starting run threads in backend
2025-01-16 13:33:11,566 INFO    Thread-2  :1617 [wandb_run.py:_console_start():2415] atexit reg
2025-01-16 13:33:11,566 INFO    Thread-2  :1617 [wandb_run.py:_redirect():2265] redirect: wrap_raw
2025-01-16 13:33:11,566 INFO    Thread-2  :1617 [wandb_run.py:_redirect():2330] Wrapping output streams.
2025-01-16 13:33:11,566 INFO    Thread-2  :1617 [wandb_run.py:_redirect():2355] Redirects installed.
2025-01-16 13:33:11,568 INFO    Thread-2  :1617 [wandb_init.py:init():910] run started, returning control to user process
2025-01-16 13:43:20,380 ERROR   Thread-1  :1617 [internal_api.py:execute():397] 502 response executing GraphQL.
2025-01-16 13:43:20,381 ERROR   Thread-1  :1617 [internal_api.py:execute():398] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2025-01-16 14:04:34,096 INFO    Thread-2  :1617 [wandb_run.py:_finish():2140] finishing run s322977-politecnico-di-torino/custom-hopper-ppo/ji9jkrkw
2025-01-16 14:04:34,097 INFO    Thread-2  :1617 [wandb_run.py:_atexit_cleanup():2380] got exitcode: 0
2025-01-16 14:04:34,097 INFO    Thread-2  :1617 [wandb_run.py:_restore():2362] restore
2025-01-16 14:04:34,097 INFO    Thread-2  :1617 [wandb_run.py:_restore():2368] restore done
2025-01-16 14:04:37,476 INFO    Thread-2  :1617 [wandb_run.py:_footer_history_summary_info():3984] rendering history
2025-01-16 14:04:37,476 INFO    Thread-2  :1617 [wandb_run.py:_footer_history_summary_info():4016] rendering summary
2025-01-16 14:04:37,478 INFO    Thread-2  :1617 [wandb_run.py:_footer_sync_info():3945] logging synced files
